version: "3.9"
services: 
  cm-car-info-svc-web: 
    restart: always
    image: "geekymon2/cm-car-info-svc"
    environment: 
      ARTIFACT_NAME: "car-info-service"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE}"
      ENVIRONMENT: "${ENVIRONMENT}"
    #local setup
    #container runs on port 8080
    #container exposing port 8880
    #container overrides APP_PORT and APP_PORT_CONTAINER when deployed
    ports:
      - "${APP_PORT:-8880}:${APP_PORT_CONTAINER:-8080}"
    depends_on: 
      - cm-car-info-svc-db
  cm-car-info-svc-db:
    hostname: "db"
    restart: always
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "${DB_PORT:-3006}:${DB_PORT_CONTAINER:-3306}"
    environment:
      MYSQL_ROOT_PASSWORD: "${CARINFO_DB_PASSWORD}"
      MYSQL_DATABASE: "${CARINFO_DB_NAME}"
      MYSQL_USER: sa
      MYSQL_PASSWORD: "${CARINFO_DB_PASSWORD}"
volumes:
  db_data: {}