version: "3.9"
services: 
  web: 
    restart: always
    image: "geekymon2/car-info-service"
    build: .
    #local setup
    #container runs on port 5000
    #container exposing port 8080
    #container overrides APP_PORT and APP_PORT_CONTAINER when deployed
    ports:
      - "${APP_PORT:-8080}:${APP_PORT_CONTAINER:-5000}"
    depends_on: 
      - car-info-service-db
  car-info-service-db:
    hostname: "car-info-service-db"
    restart: always
    image: "mcr.microsoft.com/mssql/server"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASSWORD:-P@ssw0rd}"
    #local setup
    #db container runs on port 1433
    #db container exposing port 1403
    #db container overrides DB_PORT and DB_PORT_CONTAINER when deployed
    ports:
      - "${DB_PORT:-1403}:${DB_PORT_CONTAINER:-1433}"