spring:
  application:
    name: car-info-service
  datasource:
    url: jdbc:mysql://localhost:3306/carinfodbdev
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: '{cipher}375d926fffc448580bf62d3fa5489af61c97100ceefb62f2ff58db8c0010a8ca'
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[format_sql]': true
  sql:
    init:
      platform: mysql
      data-locations: classpath:data-mysql.sql
      mode: always
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false
      retry:
        maxAttempts: 20

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

db:
  host: localhost
  port: 1111

server:
  servlet:
    context-path: ${base.context.path}