name: Build and Push to DockerHub 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildservice:
    name: Build and Push to DockerHub
    runs-on: ubuntu-latest
    steps:
    - name: generate buildnumber
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}     
    - name: checkout root  
      uses: actions/checkout@v2
      with:
        repository: geekymon2/carmarketplace
        path: carmarketplace
    - name: checkout service
      uses: actions/checkout@v2     
      with:
        path: car-info-service
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven 
    - name: build root
      run: mvn -N install --file carmarketplace/pom.xml
    - name: build service
      run: mvn -B package --file car-info-service/pom.xml -Dspring.profiles.active=test
    - name: dockerhub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: push docker image
      uses: docker/build-push-action@v2
      with:
        context: ./car-info-service
        push: true
        tags: geekymon2/car-info-service:1.0.${{ steps.buildnumber.outputs.build_number }}
        labels: ${{ steps.meta.outputs.labels }}        