name: Build and Push to DockerHub 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildservice:
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - name: checkout root  
      uses: actions/checkout@v2
      with:
        repository: geekymon2/carmarketplace
        path: carfmarketplace
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven 

    #  workingdirectory: carmarketplace
    #  run: mvn -N install --file pom.xml

  #   - name: build service
  #   - uses: actions/checkout@v2
  #     workingdirectory: service
  #     run: mvn -B package --file pom.xml -Dspring.profiles.active=test

  # push_to_registry:
  #   name: Push to Docker Hub
  #   runs-on: ubuntu-latest
  #   steps:     
  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #   needs: [buildservice]  
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: geekymon2/my-docker-hub-repository
      
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}        
