name: Manual workflow
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: [self-hosted, ci]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
